### ISSUE TITLE
"Meta viewport allows for zoom" [b4f0c3] should have secondary requirement for 1.4.10

### ISSUE THREAD

**Issue by Jym77** [auto-wcag/auto-wcag#2025]
[Meta viewport allows for zoom](https://www.w3.org/WAI/standards-guidelines/act/rules/b4f0c3) has text in the background that sounds like it should have a secondary requirement to 1.4.10, but that secondary requirement is missing.

**Comment by sboptum** [comment]
@Jym77 Is the change needed here to simply add another expandable section under the heading?

Accessibility Requirements Mapping
+ "1.4.10 Reflow (Level AA)"

**Comment by Jym77** [comment]
@sboptum A bit more 😃 
It needs to be listed as "secondary" in the frontmatter + adding a list to the SC in the Bibliography section.
See, for example, how [Meta refresh, no exception](https://raw.githubusercontent.com/act-rules/act-rules.github.io/develop/_rules/meta-refresh-no-delay-no-exception-bisz58.md) has secondary mapping to 2.2.1.

**Comment by sboptum** [comment]
@Jym77 Thank you. I'm unsure what this means "listed as "secondary" in the frontmatter".  In this [Meta refresh, no exception](https://www.w3.org/WAI/standards-guidelines/act/rules/bisz58/proposed/) I don't see anything saying "secondary" nor "frontmatter". The only references to 2.2.1 appear in the Background, Bibliography, and Mapping sections.

**Comment by Jym77** [comment]
> @Jym77 Thank you. I'm unsure what this means "listed as "secondary" in the frontmatter". In this [Meta refresh, no exception](https://www.w3.org/WAI/standards-guidelines/act/rules/bisz58/proposed/) I don't see anything saying "secondary" nor "frontmatter". The only references to 2.2.1 appear in the Background, Bibliography, and Mapping sections.

Ah, sorry for the technicalities 😅 That's about the actual markdown files, not the resulting HTML (the markdown is automagically turned into HTML when building the website).

The "frontmatter" is the initial part of the file, between the first `---` at the top of the file, and the next one, after authors and acknowledgement. IN the [Meta refresh no delay file](https://raw.githubusercontent.com/act-rules/act-rules.github.io/develop/_rules/meta-refresh-no-delay-no-exception-bisz58.md), it is this bit:
```yaml
---
id: bisz58
name: Meta element has no refresh delay (no exception)
rule_type: atomic
description: |
  This rule checks that the `meta` element is not used for delayed redirecting or refreshing.
accessibility_requirements:
  wcag20:2.2.4: # Interruptions (AAA)
    forConformance: true
    failed: not satisfied
    passed: further testing needed
    inapplicable: further testing needed
  wcag20:3.2.5: # Change on Request (AAA)
    forConformance: true
    failed: not satisfied
    passed: further testing needed
    inapplicable: further testing needed
  wcag-technique:G110: # Using an instant client-side redirect
    forConformance: false
    failed: not satisfied
    passed: further testing needed
    inapplicable: further testing needed
  wcag-technique:H76: # Using meta refresh to create an instant client-side redirect
    forConformance: false
    failed: not satisfied
    passed: further testing needed
    inapplicable: further testing needed
  wcag20:2.2.1: # Timing Adjustable (A)
    secondary: True
input_aspects:
  - DOM Tree
acknowledgments:
  authors:
    - Jean-Yves Moyen
  funding:
    - WAI-Tools
htmlHintIgnore:
  # https://www.npmjs.com/package/htmlhint
  # (used with `npm test` to ensure validity of code snippets)
  - 'title-require'
---
```
This contains all the meta-data related to the rule, including the mappings.
As you can see in the bit above the mapping to 2.2.1 as a `secondary: true` listing. This is the bit that the website generation code uses to know it is a secondary requirement 🤓
